
server:
  port: 80
  servlet:
    context-path: /coolfrog

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coolfrog?serverTimeZone=UTC
    username: coolfrog
    password: coolfrog
    type: com.alibaba.druid.pool.DruidDataSource
#  sql:
#    init:
#      mode: always
#      continue-on-error: true
#      schema-locations:
#        - "classpath:db/coolfrog_table.sql"

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto


frog:
  wx:
    appId: 
    appSecret:
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true